export const ITEMS = [
    {label: 'Rio Branco,AC', value: 'Rio Branco,AC'},
    {label: 'Maceió,AL', value: 'Maceió,AL'},
    {label: 'Macapá,AP', value: 'Macapá,AP'},
    {label: 'Manaus,AM', value: 'Manaus,AM'},
    {label: 'Salvador,BA', value: 'Salvador,BA'},
    {label: 'Fortaleza,CE', value: 'Fortaleza,CE'},
    {label: 'Brasília,DF', value: 'Brasília,DF'},
    {label: 'Vitória,ES', value: 'Vitória,ES'},
    {label: 'Goiânia,GO', value: 'Goiânia,GO'},
    {label: 'São Luís,MA', value: 'São Luís,MA'},
    {label: 'Cuiabá,MT', value: 'Cuiabá,MT'},
    {label: 'Campo Grande,MS', value: 'Campo Grande,MS'},
    {label: 'Belo Horizonte,MG', value: 'Belo Horizonte,MG'},
    {label: 'Belém,PA', value: 'Belém,PA'},
    {label: 'João Pessoa,PB', value: 'João Pessoa,PB'},
    {label: 'Curitiba,PR', value: 'Curitiba,PR'},
    {label: 'Recife,PE', value: 'Recife,PE'},
    {label: 'Teresina,PI', value: 'Teresina,PI'},
    {label: 'Rio de Janeiro,RJ', value: 'Rio de Janeiro,RJ'},
    {label: 'Natal,RN', value: 'Natal,RN'},
    {label: 'Porto Alegre,RS', value: 'Porto Alegre,RS'},
    {label: 'Porto Velho,RO', value: 'Porto Velho,RO'},
    {label: 'Boa Vista,RR', value: 'Boa Vista,RR'},
    {label: 'Florianópolis,SC', value: 'Florianópolis,SC'},
    {label: 'São Paulo,SP', value: 'São Paulo,SP'},
    {label: 'Aracaju,SE', value: 'Aracaju,SE'},
    {label: 'Palmas,TO', value: 'Palmas,TO'},
    
  ]